version: 1.0.{build}
os: Windows Server 2012 R2
# enable patching of AssemblyInfo.* files
#assembly_info:
#  patch: true
#  file: AssemblyInfo.*
#  assembly_version: "{version}"
#  assembly_file_version: "{version}"
#  assembly_informational_version: "{version}"
artifacts:
  # - path: standalone/bin/slua-standalone.zip
  #   name: slua-standalone
  - path: '*.nupkg'
    name: slua-standalone-nupkg
build_script:
- cmd: .\standalone\msbuild_vs2012.bat
after_build:
  # slua-standalone
  - cmd: set BASE=%~dp0
  # unit tests
  - cmd: standalone\unit_tests.bat
  # - cmd: cd standalone\bin
  # - cmd: nunit3-console slua-standalone-tests.dll --result=testresults.xml;format=AppVeyor
  # - cmd: 7z a slua-standalone.zip slua-standalone.dll
  # - cmd: 7z a slua-standalone.zip slua-standalone.pdb
  # - cmd: 7z a slua-standalone.zip slua.dll
  # - cmd: 7z a slua-standalone.zip slua.so
  # - cmd: 7z a slua-standalone.zip slua-standalone.dll.config
  # - cmd: 7z a slua-standalone.zip SLUA_README.txt
  # - cmd: cd %BASE%
  # nupkg -> \slua-standalone.x.x.x.nupkg
  - cmd: nuget pack standalone\slua-standalone.nuspec -Version %APPVEYOR_BUILD_VERSION%
test: off
deploy:
- provider: Environment
  name: Github
  # tag: slua.$(appveyor_build_version)
  on:
    branch: master                # release from master branch only
    appveyor_repo_tag: true       # deploy on tag push only
- provider: Environment
  name: nuget.org
